import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { BottomNav } from '../components/ui';
import { useApp } from '../context/AppContext';
const rows = [['bell-outline', 'Notification settings'], ['ruler', 'Preferred units'], ['information-outline', 'About']];
export default function Profile() { const { setLoggedIn } = useApp(); const tap = () => Alert.alert('Coming soon', 'This setting is not available in the demo.'); const logout = () => { setLoggedIn(false); router.replace('/login'); }; return <SafeAreaView style={styles.safe}><View style={styles.header}><Text style={styles.eyebrow}>ACCOUNT</Text><Text style={styles.title}>Profile</Text></View><View style={styles.profile}><View style={styles.avatar}><Text style={styles.avatarText}>AM</Text></View><View><Text style={styles.name}>Alex Morgan</Text><Text style={styles.email}>hiker@trailhead.com</Text><Text style={styles.hiked}>12 trails hiked</Text></View></View><View style={styles.settings}>{rows.map(([icon, title]) => <Pressable key={title} onPress={tap} style={styles.row}><MaterialCommunityIcons name={icon} size={21} color="#27705C" style={styles.rowIcon} /><Text style={styles.rowText}>{title}</Text><MaterialCommunityIcons name="chevron-right" size={24} color="#A1ABA6" /></Pressable>)}<Pressable onPress={logout} style={styles.row}><MaterialCommunityIcons name="logout" size={21} color="#B54F42" style={styles.rowIcon} /><Text style={[styles.rowText, { color: '#B54F42' }]}>Log out</Text></Pressable></View><BottomNav /></SafeAreaView>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: '#F7F6F0' }, header: { padding: 22, paddingTop: 18 }, eyebrow: { fontSize: 11, letterSpacing: 1.6, color: '#276B58', fontWeight: '800' }, title: { fontSize: 31, fontWeight: '800', color: '#17342D', marginTop: 5 }, profile: { backgroundColor: '#E6EFE8', marginHorizontal: 22, borderRadius: 18, padding: 20, flexDirection: 'row', alignItems: 'center', gap: 15 }, avatar: { width: 63, height: 63, borderRadius: 32, backgroundColor: '#2B715D', alignItems: 'center', justifyContent: 'center' }, avatarText: { color: 'white', fontWeight: '800', fontSize: 19 }, name: { fontSize: 20, fontWeight: '800', color: '#1D3D34' }, email: { color: '#60736A', fontSize: 13, marginTop: 2 }, hiked: { color: '#20705B', fontWeight: '800', fontSize: 13, marginTop: 8 }, settings: { backgroundColor: 'white', margin: 22, borderRadius: 16, overflow: 'hidden', borderWidth: 1, borderColor: '#E7E5DF' }, row: { height: 61, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: '#EFEEE9' }, rowIcon: { width: 29, fontSize: 20, color: '#27705C', textAlign: 'center' }, rowText: { flex: 1, marginLeft: 11, color: '#304B42', fontWeight: '600', fontSize: 15 }, arrow: { fontSize: 26, color: '#A1ABA6' } });


