import { Image, Linking, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { trails, difficultyColor } from '../../data/trails';
import { useApp } from '../../context/AppContext';
export default function TrailDetails() {
  const { id } = useLocalSearchParams(); const trail = trails.find((item) => item.id === id) || trails[0]; const { savedIds, toggleSaved } = useApp(); const saved = savedIds.includes(trail.id);
  const startNavigation = () => Linking.openURL(`https://www.google.com/maps/dir/?api=1&destination=${trail.coords.latitude},${trail.coords.longitude}&travelmode=walking`);
  return <SafeAreaView style={styles.safe}><ScrollView showsVerticalScrollIndicator={false}><View style={styles.hero}><Image source={{ uri: trail.image }} style={styles.image} /><View style={styles.heroShade} /><Pressable onPress={() => router.back()} style={styles.back}><MaterialCommunityIcons name="arrow-left" size={25} color="#254138" /></Pressable><Pressable onPress={() => toggleSaved(trail.id)} style={styles.save}><MaterialCommunityIcons name={saved ? "star" : "star-outline"} size={27} color={saved ? "#E4AC32" : "#476259"} /></Pressable></View><View style={styles.body}><View style={styles.titleRow}><Text style={styles.title}>{trail.name}</Text><Text style={[styles.tag, { color: difficultyColor[trail.difficulty], borderColor: difficultyColor[trail.difficulty] }]}>{trail.difficulty}</Text></View><View style={styles.stats}>{[[trail.distance, 'DISTANCE'], [trail.elevation, 'ELEVATION'], [trail.time, 'EST. TIME']].map(([value, label]) => <View key={label} style={styles.stat}><Text style={styles.statValue}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View>)}</View><View style={styles.section}><Text style={styles.sectionTitle}>About this trail</Text><Text style={styles.description}>{trail.description}</Text></View><View style={styles.section}><Text style={styles.sectionTitle}>Trail map</Text><View style={styles.map}><View style={styles.mapLines}><View style={styles.route} /></View><View style={styles.pin}><MaterialCommunityIcons name="map-marker" size={18} color="white" /></View><View style={styles.mapLabel}><Text style={styles.mapLabelText}>Route preview</Text></View></View><Text style={styles.coordinates}>Map center · {trail.coords.latitude.toFixed(3)}, {trail.coords.longitude.toFixed(3)}</Text></View></View></ScrollView><View style={styles.footer}><Pressable onPress={startNavigation} style={styles.navigate}><MaterialCommunityIcons name="navigation-variant" size={21} color="white" /><Text style={styles.navigateText}>Start navigation</Text></Pressable></View></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: '#F7F6F0' }, hero: { height: 275 }, image: { width: '100%', height: '100%' }, heroShade: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(0,0,0,.12)' }, back: { position: 'absolute', top: 15, left: 18, width: 42, height: 42, borderRadius: 21, backgroundColor: 'rgba(255,255,255,.94)', alignItems: 'center', justifyContent: 'center' }, backText: { fontSize: 36, color: '#254138', lineHeight: 38, marginBottom: 5 }, save: { position: 'absolute', top: 15, right: 18, width: 42, height: 42, borderRadius: 21, backgroundColor: 'rgba(255,255,255,.94)', alignItems: 'center', justifyContent: 'center' }, saveText: { fontSize: 28, color: '#476259' }, body: { padding: 22, paddingBottom: 30 }, titleRow: { flexDirection: 'row', alignItems: 'center', gap: 10 }, title: { fontSize: 26, letterSpacing: -.5, fontWeight: '800', color: '#17342D', flexShrink: 1 }, tag: { borderWidth: 1, borderRadius: 99, fontSize: 12, fontWeight: '800', paddingHorizontal: 8, paddingVertical: 4, overflow: 'hidden' }, stats: { flexDirection: 'row', marginTop: 22, backgroundColor: '#E8F0E9', borderRadius: 14, paddingVertical: 14 }, stat: { flex: 1, alignItems: 'center', borderRightWidth: 1, borderColor: '#C9D9CC' }, statValue: { color: '#21463A', fontWeight: '800', fontSize: 14 }, statLabel: { color: '#678077', fontSize: 9, letterSpacing: .6, fontWeight: '800', marginTop: 5 }, section: { marginTop: 28 }, sectionTitle: { color: '#183A30', fontSize: 19, fontWeight: '800', marginBottom: 9 }, description: { color: '#5F7069', fontSize: 15, lineHeight: 23 }, map: { height: 178, borderRadius: 15, backgroundColor: '#D8E6D6', overflow: 'hidden', justifyContent: 'center', alignItems: 'center' }, mapLines: { ...StyleSheet.absoluteFillObject, backgroundColor: '#C7DABF', opacity: .65 }, route: { height: 260, width: 80, borderRadius: 65, borderWidth: 6, borderColor: '#227159', transform: [{ rotate: '35deg' }], position: 'absolute', left: '39%', top: -43 }, pin: { width: 30, height: 30, borderRadius: 15, backgroundColor: '#D7654C', alignItems: 'center', justifyContent: 'center', borderWidth: 3, borderColor: 'white' }, mapLabel: { position: 'absolute', bottom: 11, left: 11, backgroundColor: 'rgba(255,255,255,.91)', paddingHorizontal: 9, paddingVertical: 5, borderRadius: 6 }, mapLabelText: { fontSize: 11, color: '#365249', fontWeight: '700' }, coordinates: { color: '#86928D', fontSize: 11, marginTop: 7 }, footer: { padding: 15, borderTopWidth: 1, borderColor: '#E5E4DE', backgroundColor: '#FEFDF9' }, navigate: { height: 54, backgroundColor: '#176B56', borderRadius: 12, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 8 }, navigateIcon: { color: 'white', fontSize: 21 }, navigateText: { color: 'white', fontWeight: '800', fontSize: 16 } });


